/*
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractRankPLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(pl.stolorz.dsl.rankpl.rankPL.RankPLPackage.eINSTANCE);
		return result;
	}
	
}
