/*
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import pl.stolorz.dsl.rankpl.ui.internal.RankplActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RankPLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RankplActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RankplActivator.getInstance().getInjector(RankplActivator.PL_STOLORZ_DSL_RANKPL_RANKPL);
	}
	
}
