/*
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RankPLRuntimeModule extends AbstractRankPLRuntimeModule {
}
