/*
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import pl.stolorz.dsl.rankpl.ui.internal.RankplActivator;

public class RankPLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RankplActivator.getInstance().getInjector("pl.stolorz.dsl.rankpl.RankPL");
	}

}
