/*
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RankPLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("pl/stolorz/dsl/rankpl/parser/antlr/internal/InternalRankPL.tokens");
	}
}
