/*
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import pl.stolorz.dsl.rankpl.parser.antlr.internal.InternalRankPLParser;
import pl.stolorz.dsl.rankpl.services.RankPLGrammarAccess;

public class RankPLParser extends AbstractAntlrParser {

	@Inject
	private RankPLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_HASH_COMMENT");
	}
	

	@Override
	protected InternalRankPLParser createParser(XtextTokenStream stream) {
		return new InternalRankPLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RankPLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RankPLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
