/*
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRankPLScopeProvider extends DelegatingScopeProvider {
}
