/**
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.rankPL.impl;

import org.eclipse.emf.ecore.EClass;

import pl.stolorz.dsl.rankpl.rankPL.DeclaredParameter;
import pl.stolorz.dsl.rankpl.rankPL.RankPLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Declared Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DeclaredParameterImpl extends AbstractDefinitionImpl implements DeclaredParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclaredParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RankPLPackage.Literals.DECLARED_PARAMETER;
  }

} //DeclaredParameterImpl
