/*
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.scoping

import org.eclipse.emf.ecore.EReference
import javax.swing.text.View
import org.eclipse.xtext.scoping.Scopes

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class RankPLScopeProvider extends AbstractRankPLScopeProvider {


}
