/**
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.rankPL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declared Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pl.stolorz.dsl.rankpl.rankPL.RankPLPackage#getDeclaredParameter()
 * @model
 * @generated
 */
public interface DeclaredParameter extends AbstractDefinition
{
} // DeclaredParameter
