/**
 * generated by Xtext 2.11.0
 */
package pl.stolorz.dsl.rankpl.rankPL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pl.stolorz.dsl.rankpl.rankPL.RankPLPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
